version: "3.9"
services:
  felinify:
    image: felinify
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
